export { default as LoginScreen } from './login/Login';
export { default as Dashboard } from './admin/Dashboard/Dashboard';
export { default as PageNotFound } from './404/404';
export { default as QuestionPapers } from './exam/questionPapers/QuestionPapers';
export { default as AssignedExams } from './exam/assignedExams/AssignedExams';
// export { default as PublishExam } from './exam/PublishExam';
export { default as EnrollStudent } from './enrollStudent/EnrollStudent';
export { default as EnrollFaculty } from './enrollFaculty/EnrollFaculty';
export { default as Reports } from './reports/Reports';
export { default as LiveLecture } from './liveLecture/LiveLecture';
export { default as TermsPrivacyPolicy } from './termsPrivacyPolicy/TermsPrivacyPolicy';
export { default as Trash } from './trash/Trash';